messages:
  basename: ValidationMessages

spring.profiles.active: test
server.port: 8090

logging.level:
  com.trendyol.Case2: trace

# Couchbase Settings
spring:
  data:
    couchbase.auto-index: true
case2:
  couchbase:
    host-name: 127.0.0.1
    default-host-name: localhost
    bucket-pass: jfFMd8Nd