spring.profiles.active: dev

# Mongo Settings
case2:
  mongo.host-name: "127.0.0.1"
  mongo.password: "LJYKkAw6b3TtQt3f"
  mongo.port: "27017"
  mongo.username: "secretUser"
  mongo.database: "secretDb"